<a href="https://colab.research.google.com/github/rlopezortega/Programacion/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

el pandas serveiz per treballar amb dades, i tenim tres tipus d'estructures:
- series: estructutres d'una dimensio que porten el seu index associat a les segones
- Data frames: estructures de dues dimensions
- panells: tres dimensions

per instalar el pandas a colab

pip install pandas

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
!python --version

Python 3.10.12

In [ ]:
!apt-get install python3.12

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3.12 is already the newest version (3.12.7-1+jammy1).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.

In [ ]:
import pandas as pd

setmana= pd.Series(["dilluns","dimarts","dimecres","dijous","divendres","dissabte","diumenge"])

print(setmana)
print((setmana.dtype))

print(setmana[0])

print(setmana[0])
print(setmana[2])
print(setmana[4])
print(setmana[6])

0      dilluns
1      dimarts
2     dimecres
3       dijous
4    divendres
5     dissabte
6     diumenge
dtype: object
object
dilluns
dilluns
dimecres
divendres
diumenge

In [ ]:
import pandas as pd

serie= pd.Series([12,58,63,47,81,35])

print(serie)

suma_serie = serie.sum()
print("L’import total és:", suma_serie)

media=serie.mean()
print(round(media,2))

raro = serie.value_counts()
print(raro)

max = serie.max()
print(max)

min = serie.min()
print(min)

raro_dos = serie.cumsum()
print(raro_dos)

0    12
1    58
2    63
3    47
4    81
5    35
dtype: int64
L’import total és: 296
49.33
12    1
58    1
63    1
47    1
81    1
35    1
Name: count, dtype: int64
81
12
0     12
1     70
2    133
3    180
4    261
5    296
dtype: int64

In [ ]:
import pandas as pd

llista = pd.DataFrame([{"Nombre":"Pedro","Edat":25, "Altura":1.68},
                      {"Nombre":"Sonia","Edat":52, "Altura":1.74},
                      {"Nombre":"Luis","Edat":19, "Altura":1.81},
                      {"Nombre":"Marta","Edat":33, "Altura":1.59},
                      {"Nombre":"Julian","Edat":48, "Altura":1.71},
                      {"Nombre":"Nerea","Edat":61, "Altura":1.78},
                      ])
llista

   Nombre  Edat  Altura
0   Pedro    25    1.68
1   Sonia    52    1.74
2    Luis    19    1.81
3   Marta    33    1.59
4  Julian    48    1.71
5   Nerea    61    1.78

In [ ]:
import pandas as pd

data = {
    'Nombre': ['Pedro', 'Sonia', 'Luis', 'Marta', 'Julian', 'Nerea'],
    'Edad': [25, 52, 19, 33, 48, 61],
    'Altura': [1.68, 1.74, 1.81, 1.59, 1.71, 1.78],
    'Institut': ['MVM', 'MVM', 'MVM', 'MVM', 'MVM', 'MVM']
}

dataframe = pd.DataFrame(data)

# Crear una nueva columna 'Edat2' sumando 2 a la columna 'Edad'
data["Horas d'estudi fora de l'institut"] = [2, 4, 1, 1/2, 0, 3 ]

dataframe = pd.DataFrame(data)

print(dataframe)

   Nombre  Edad  Altura Institut  Horas d'estudi fora de l'institut
0   Pedro    25    1.68      MVM                                2.0
1   Sonia    52    1.74      MVM                                4.0
2    Luis    19    1.81      MVM                                1.0
3   Marta    33    1.59      MVM                                0.5
4  Julian    48    1.71      MVM                                0.0
5   Nerea    61    1.78      MVM                                3.0